enviroair/enviroair/purchase_order/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.PurchaseOrderListView.as_view(), name="purchase-order-list"),
    path('<int:pk>/', views.PurchaseOrderDetailView.as_view(), name="purchase-order-detail"),
    path('create/', views.PurchaseOrderCreateView.as_view(), name="purchase-order-create"),
    path('update/<int:pk>/', views.PurchaseOrderUpdateView.as_view(), name="purchase-order-update"),
    path('delete/<int:pk>/', views.PurchaseOrderDeleteView.as_view(), name="purchase-order-delete"),
]

enviroair/enviroair/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from .purchase_order.urls import urlpatterns as purchase_order_urls

urlpatterns = [
    path('dashboardadmin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('purchaseorders/', include((purchase_order_urls, 'purchase_order'), namespace='purchase_order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)
    # urlpatterns += staticfiles_urlpatterns()

enviroair/enviroair/purchase_order/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


# sort order (manual configure and then alphabetical)
class SortableModel(models.Model):
    sort_order = models.PositiveIntegerField(null=True, blank=True, )

    class Meta:
        abstract = True
        ordering = ['sort_order']


class Job(SortableModel):
    created = models.DateTimeField(default=now)

    name = models.CharField(max_length=250)

    number = models.SlugField(max_length=255, unique=True)

    class Meta(SortableModel.Meta):
        # sort order (manual configure and then alphabetical)
        ordering = SortableModel.Meta.ordering + ['name']

    # an other selections field and
    # free text field for other jobs

    # file import for first start (from CSV)

    def __str__(self):
        return f"{self.name}"


class Supplier(SortableModel):
    name = models.CharField(max_length=250)

    class Meta(SortableModel.Meta):
        # sort order (manual configure and then alphabetical)
        ordering = SortableModel.Meta.ordering + ['name']

    # an other selections field and
    # free text field for other suppliers

    # file import for first start (from CSV)

    """email  = models.EmailField(blank=True, default="")"""

    def __str__(self):
        return f"{self.name}"


class PurchaseOrder(models.Model):
    created = models.DateTimeField(default=now)

    number = models.SlugField(max_length=255, unique=True)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="purchase_orders",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    job = models.ForeignKey(
        Job,
        related_name="purchase_orders",
        null=True,
        on_delete=models.SET_NULL,
    )

    supplier = models.ForeignKey(
        Supplier,
        related_name="purchase_orders",
        null=True,
        on_delete=models.SET_NULL,
    )

    description = models.TextField(blank=True)

    class Meta:
        ordering = ['-created', '-number']

    def __str__(self):
        return f"{self.number} - {self.supplier} - {self.created.strftime('%d %b %Y')}"

    def get_absolute_url(self):
        return reverse('purchase_order:purchase-order-detail', kwargs={'pk': self.pk})

enviroair/enviroair/purchase_order/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Job, Supplier, PurchaseOrder
from .utils import get_unique_purchase_order_number


class PurchaseOrderListView(ListView):
    model = PurchaseOrder
    paginate_by = 10


class PurchaseOrderDetailView(DetailView):
    model = PurchaseOrder


class PurchaseOrderCreateView(PermissionRequiredMixin, CreateView):
    model = PurchaseOrder
    fields = ['supplier', 'job', 'description']
    success_message = 'Purchase Order was created successfully. Please use: %(number)'
    permission_required = 'purchase_order.can_create'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.number = get_unique_purchase_order_number(PurchaseOrder)
        return super().form_valid(form)


class PurchaseOrderUpdateView(PermissionRequiredMixin, UpdateView):
    model = PurchaseOrder
    fields = ['number', 'supplier', 'job', 'description']
    success_message = 'Purchase Order %(number)s was updated successfully'
    permission_required = 'purchase_order.can_update'


class PurchaseOrderDeleteView(PermissionRequiredMixin, DeleteView):
    model = PurchaseOrder
    success_url = reverse_lazy('purchase_order:purchase-order-list')
    permission_required = 'purchase_order.can_delete'

enviroair/templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
{% load bootstrap4 %}

<html lang="en" class="no-js">
<head>
    <title>{% block title %}{{ site.name }}{% endblock %}</title>
    {% block meta %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Saleor">
    <meta name="theme-color" content="#333333">
    <meta name="msapplication-TileColor" content="#2b5797">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="{{ site.name }}">
    <meta name="og:type" content="website">
    {% endblock meta %}

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">


    {% block stylesheet %}{% endblock stylesheet %}

    {% block meta_tags %}
    <meta property="og:title" content="{{ site.settings.translated.header_text }}">
    <meta property="og:description" content="{{ site.settings.translated.description }}">
    <meta name="description" content="{{ site.settings.translated.description }}">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:image" content="{% static 'images/block1.png' %}">
    {% endblock meta_tags %}

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<body>
{% block header %}
<header class="navbar" role="navigation">
    <img src="{% static 'images/logo-bg.png' %}" class="lazyload lazypreload"
         data-src="{% static 'images/logo-bg.png' %}"
         data-srcset="{% static 'images/logo-bg.png' %} 1x, {% static 'images/logo-bg2x.png' %} 2x">
    <div class="navbar__login container-fluid {% if user.is_impersonate %} bg-warning {% endif %}">
        <div class=" d-none d-md-block container">
            <div class="row">
                <div class="col-6">
                    <p class="text-left">{{ site.settings.translated.header_text }}</p>
                </div>
                <div class="col-6">
                    <ul class="float-right">
                        {% if user.is_authenticated %}
                        {% if user.is_staff or request.impersonator.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}" target="_blank" rel="noopener">
                                {% trans "Admin" context "Main navigation item" %}
                            </a>
                        </li>
                        {% endif %}
                        <li>
                            <a href="{ url account:details }">
                                {% trans "Your account" context "Main navigation item" %}</a>
                        </li>
                        {% if user.is_impersonate %}
                        <li>
                            <a href="{ url impersonate-stop }">
                                {% trans 'Stop impersonating' context 'Main navigation item' %}
                            </a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{% url 'logout' %}">
                                {% trans "Log out" context "Main navigation item" %}</a>
                        </li>
                        {% endif %}
                        {% else %}
                        <li>
                            <a rel="nofollow" href="{% url 'login' %}">
                                {% trans "Log in" context "Main navigation item" %}
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar__brand container-fluid d-block">
        <div class="container">
            <div class="row no-gutters">
                <div class="col-8 col-md-4 navbar__logo">
                    <div class="menu-icon-mobile d-md-none navbar__brand__menu-toggle closed open">
                        <svg data-src="{% static 'images/mobile-menu.svg' %}" width="28px" height="20px"/>
                    </div>
                    <a href="{ url 'home' }">
                        <svg data-src="{% static 'images/logo-light.svg' %}"/>
                    </a>
                </div>

            </div>
        </div>
    </div>
    <div class="navbar__menu container d-block">
        <nav class="navigation">
            <nav class="navbar navbar-expand-md navbar-light bg-light">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <button class="btn btn-outline-success" type="button">
                            Home <span class="sr-only">(current)</span>
                        </button>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-success nav-link" href="#">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-success nav-link" href="#">Pricing</a>
                    </li>
                </ul>
            </nav>
        </nav>
    </div>
</header>
{% endblock %}
<div class="container maincontent">
    {% block topcontent %}{% endblock topcontent %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    {% block breadcrumb %}
    {% endblock breadcrumb %}
    {% block content %}
    {% endblock content %}

</div>

{% block footer %}
<footer class="footer">
    <div class="footer__menus">
        <div class="container">
            <div class="row">
                <p>Footer Menu stuff goes here originally</p>
                <div class="col-md-2 col-6">
                    <ul class="menu">
                        <li class="nav-item__dropdown menu__item">
                            <a>
                                <strong>
                                    {% trans "Account" %}
                                </strong>
                            </a>
                            <hr/>
                            {% if user.is_authenticated %}
                            {% if user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}" target="_blank" rel="noopener">
                                {% trans "Admin" context "Main navigation item" %}
                            </a>
                        </li>
                        {% endif %}
                        <li>
                            <a href="{ url account:details }">
                                {% trans "Your account" context "Main navigation item" %}
                            </a>
                        </li>
                        {% if user.is_impersonate %}
                        <li>
                            <a href="{ url impersonate-stop }">
                                {% trans 'Stop impersonating' context 'Main navigation item' %}
                            </a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{% url 'logout' %}">
                                {% trans "Log out" context "Main navigation item" %}</a>
                        </li>
                        {% endif %}
                        {% else %}
                        <li>
                            <a rel="nofollow" href="{% url 'login' %}">
                                {% trans "Log in" context "Main navigation item" %}
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <div class="offset-md-2 col-md-4 col-12">
                    <div class="footer__menus__social-container">
                        <!---<div class="footer__menus__social">
                          <a target="_blank" rel="noopener" class="social-footer" href="https://github.com/mirumee/saleor">
                            <svg data-src="{% static "images/github-logo.svg" %}" width="45px" height="45px"/>
                          </a>
                          <a target="_blank" rel="noopener" class="social-footer" href="https://linkedin.com/company/mirumee-software">
                            <svg data-src="{% static "images/linkedin-logo.svg" %}" width="45px" height="45px"/>
                          </a>
                        </div>--->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer__copy">
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <a href="{ url 'home' }" class="footer__logo float-md-left">
                        <svg data-src="{% static 'images/logo-light.svg' %}"/>
                    </a>
                </div>
                <div class="col-8 footer__copy-text">COPYRIGHT © 2020 QUARK INTERACTIVE</div>
            </div>
        </div>
    </div>
</footer>
{% endblock %}
{% block footer_scripts %}
{% endblock footer_scripts %}
</body>
</html>

enviroair/templates/purchase_order/purchaseorder_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Purchase Order</h1>

<p>Are you sure you want to delete the purchase order: {{ purchaseorder }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

<a href="{% url "purchase_order:purchase-order-update" purchaseorder.pk %}">
  Update
</a>
<a href="{% url "purchase_order:purchase-order-list" %}">
  List
</a>

{% endblock %}

enviroair/templates/purchase_order/purchaseorder_detail.html
{% extends "base.html" %}

{% block content %}

<h2>Purchase Order</h2>

<h1># {{ purchaseorder.number }}</h1>
<h3>{{ purchaseorder.supplier }}</h3>
<br/>
<p>Created by: {{ purchaseorder.user }}</p>
<p>At: {{ purchaseorder.created }}</p>

<a href="{% url "purchase_order:purchase-order-update" purchaseorder.pk %}">
  Update
</a>
<a href="{% url "purchase_order:purchase-order-list" %}">
  List
</a>
        
{% endblock %}

enviroair/templates/purchase_order/purchaseorder_form.html
{% extends "base.html" %}

{% load static %}
{% load static %}
{% load bootstrap4 %}

{% block content %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
        Submit
    </button>
    <button type="reset" class="btn btn-primary">
        Reset
    </button>
    {% endbuttons %}

</form>
{% endblock %}

enviroair/templates/purchase_order/purchaseorder_list.html
{% extends "base.html" %}

{% block content %}

<h1>Purchase Order List</h1>



{% if purchaseorder_list %}
<table class="table">
    <tbody>

    {% for purchaseorder in purchaseorder_list %}
    <tr>
        <td>
            <a href="{{ purchaseorder.get_absolute_url }}">
                {{ purchaseorder.number }}
            </a>
        </td>
        <td>
            <a href="{{ purchaseorder.get_absolute_url }}">
                {{ purchaseorder.supplier }}
            </a>
        </td>
        <td>
            <a href="{{ purchaseorder.get_absolute_url }}">
                {{ purchaseorder.created }}
            </a>
        </td>
    </tr>
    {% endfor %}

    </tbody>
</table>
{% else %}
<p>There are no purchase orders available.</p>
{% endif %}


{% endblock %}